server:
  port: 9091
  
spring:
  data:
    mongodb:
      #authentication-database: admin
      #uri: mongodb://localhost:27017
      host: localhost
      port: 27017
      database: mongoDB_Demo
      #username: 
      #password:
